backend:
  name: github
  repo: zaidprd/zaidly
  branch: main
  base_url: https://zaidly-auth.ahmadzaid-tamiang.workers.dev
  auth_endpoint: auth

# Baris wajib agar ada tombol Save (Draft)
publish_mode: editorial_workflow

media_folder: "src/assets/images/blog"
public_folder: "/src/assets/images/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "SEO Description", name: "description", widget: "string", required: true }
      - { label: "Publish Date", name: "pub_date", widget: "datetime", required: true }
      - { 
          label: "Category", 
          name: "category", 
          widget: "select", 
          options: ["gear-lab", "bean-roastery", "brew-mastery", "barista-life", "buying-guides"], 
          required: true 
        }
      - { label: "Author Name", name: "author", widget: "string", required: true }
      - { label: "Feature Image URL", name: "image", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: true }