backend:
  name: github
  repo: zaidprd/zaidly
  branch: main
  base_url: https://zaidly-auth.ahmadzaid-tamiang.workers.dev
  auth_endpoint: auth
local_backend: true

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

publish_mode: editorial_workflow
media_folder: "src/assets/images/blog"
public_folder: "/src/assets/images/blog"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    extension: "mdx" # Ubah ke mdx agar support tombol
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "SEO Friendly Slug", name: "slug_seo", widget: "string", required: false }
      - { label: "SEO Description", name: "description", widget: "string", required: true }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", required: true }
      - { 
          label: "Category", 
          name: "category", 
          widget: "select", 
          options: ["gear-lab", "bean-roastery", "brew-mastery", "barista-life", "buying-guides"], 
          required: true 
        }
      - { label: "Author Name", name: "author", widget: "string", required: true, default: "admin" }
      - { label: "Feature Image URL", name: "image", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false, default: ["bean roastery"] }
      - { 
          label: "Body", 
          name: "body", 
          widget: "markdown", 
          required: true,
          default: "import AffiliateLink from '../../components/AffiliateLink.astro';\n\n"
        }